version: "3.9"

services:
  backend:
    image: ghcr.io/${GITHUB_USER}/backend:latest
    container_name: violeta-backend
    ports:
      - "8080:8080"
    env_file: .env.backend

  frontend:
    image: ghcr.io/${GITHUB_USER}/frontend:latest
    container_name: violeta-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
